version: "3.5"
services:
        dexpy:
                build: ./
                image: dexpy:latest
                privileged: True
                volumes:
                        - /dev/bus/usb:/dev/bus/usb
                environment:
                        - DEXCOM_SHARE_SERVER=
                        - DEXCOM_SHARE_USERNAME=
                        - DEXCOM_SHARE_PASSWORD=
                        - MQTT_SERVER=
                        - MQTT_PORT=
                        - MQTT_SSL=
                        - MQTT_CLIENTID=
                        - MQTT_TOPIC=
                        - INFLUXDB_SERVER=
                        - INFLUXDB_PORT=
                        - INFLUXDB_SSL=
                        - INFLUXDB_USERNAME=
                        - INFLUXDB_PASSWORD=
                        - INFLUXDB_DATABASE=
                        - NIGHTSCOUT_URL=
                        - NIGHTSCOUT_SECRET=
                        - NIGHTSCOUT_TOKEN=
                        - LOG_LEVEL=DEBUG
